//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Status_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Самолет.
    /// </summary>
    // *** Start programmer edit section *** (Самолет CustomAttributes)

    // *** End programmer edit section *** (Самолет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СамолетE", new string[] {
            "Назв as \'Назв\'",
            "Продажа as \'Продажа\'"})]
    [View("СамолетL", new string[] {
            "Назв as \'Назв\'",
            "Продажа as \'Продажа\'"})]
    public class Самолет : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазв;
        
        private IIS.Status_2.Статус fПродажа;
        
        // *** Start programmer edit section *** (Самолет CustomMembers)

        // *** End programmer edit section *** (Самолет CustomMembers)

        
        /// <summary>
        /// Назв.
        /// </summary>
        // *** Start programmer edit section *** (Самолет.Назв CustomAttributes)

        // *** End programmer edit section *** (Самолет.Назв CustomAttributes)
        [StrLen(255)]
        public virtual string Назв
        {
            get
            {
                // *** Start programmer edit section *** (Самолет.Назв Get start)

                // *** End programmer edit section *** (Самолет.Назв Get start)
                string result = this.fНазв;
                // *** Start programmer edit section *** (Самолет.Назв Get end)

                // *** End programmer edit section *** (Самолет.Назв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Самолет.Назв Set start)

                // *** End programmer edit section *** (Самолет.Назв Set start)
                this.fНазв = value;
                // *** Start programmer edit section *** (Самолет.Назв Set end)

                // *** End programmer edit section *** (Самолет.Назв Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        // *** Start programmer edit section *** (Самолет.Продажа CustomAttributes)

        // *** End programmer edit section *** (Самолет.Продажа CustomAttributes)
        public virtual IIS.Status_2.Статус Продажа
        {
            get
            {
                // *** Start programmer edit section *** (Самолет.Продажа Get start)

                // *** End programmer edit section *** (Самолет.Продажа Get start)
                IIS.Status_2.Статус result = this.fПродажа;
                // *** Start programmer edit section *** (Самолет.Продажа Get end)

                // *** End programmer edit section *** (Самолет.Продажа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Самолет.Продажа Set start)

                // *** End programmer edit section *** (Самолет.Продажа Set start)
                this.fПродажа = value;
                // *** Start programmer edit section *** (Самолет.Продажа Set end)

                // *** End programmer edit section *** (Самолет.Продажа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СамолетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СамолетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СамолетE", typeof(IIS.Status_2.Самолет));
                }
            }
            
            /// <summary>
            /// "СамолетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СамолетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СамолетL", typeof(IIS.Status_2.Самолет));
                }
            }
        }
    }
}
